### PR TITLE
fix(macros): resolve conflict lifetime name in service with lifetime a and events

### LINKED ISSUE #341: bug(macros): conflict lifetime name in service with lifetime `a` and events
### Problem

```
#[gservice(events = SvcEvents)]
impl<'a> IncDecSvc<'a> {
```

```
error[E0496]: lifetime name `'a` shadows a lifetime name that is already in scope
  --> examples\counter\app\src\incdec.rs:16:1
   |
16 | #[gservice(events = SvcEvents)]
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ lifetime `'a` already in scope
17 | impl<'a> IncDecSvc<'a> {
   |                    -- first declared here
   |
   = note: this error originates in the attribute macro `gservice` (in Nightly builds, run with -Z macro-backtrace for more info)
```

### Steps

1. impl service w. lifetime `a` and events

### Possible Solution

_No response_

### Notes

_No response_

### Relevant Log Output

_No response_

### PR DESCRIPTION
**Pull request by vobradovich**
Resolves #341 .

### CODE REVIEW

File: macros/core/src/shared.rs [hunk 1]
```diff
@@ -175,3 +176,17 @@ pub(crate) fn generate_unexpected_input_panic(input_ident: &Ident, message: &str
         panic!(#message_pattern, input)
     })
 }
+
+pub(crate) fn extract_lifetime_names(type_args: AngleBracketedGenericArguments) -> Vec<String> {
```
Comment (DennisInSky) [inline macros/core/src/shared.rs:180]: I would pass `&PathArguments`
```suggestion
pub(crate) fn extract_lifetime_names(type_args: &PathArguments) -> Vec<String> {
```

File: macros/core/tests/gservice.rs [hunk 2]
```diff
@@ -82,3 +82,25 @@ fn works_with_events() {
 
     insta::assert_snapshot!(result);
 }
+
+#[test]
+fn works_withworks_with_lifetimes_generics_events() {
```
Comment (DennisInSky) [inline macros/core/tests/gservice.rs:87]: Naming `works_withworks_with`

File: macros/tests/gservice_tests.rs [hunk 3]
```diff
@@ -164,3 +165,32 @@ fn gservice_with_events() {
     assert_eq!(events.len(), 1);
     assert_eq!(events[0], MyEvents::Event1);
 }
+
+#[tokio::test]
+async fn gservice_with_lifecycles_generics_events() {
```
Comment (DennisInSky) [inline macros/tests/gservice_tests.rs:170]:
```suggestion
async fn gservice_with_lifecycles_and_events() {
```

**Review by DennisInSky — APPROVED** [review]
