### PR TITLE
fix(client-gen): Pass paths with AsRef<Path>

### LINKED ISSUE #180: Use `AsRef<Path>` instead of `&Path` in API
### File Location(s)

`sails_clientgen::generate_client_from_idl`

### Proposal

Any API works with system paths uses `AsRef<Path>` in function signatures (check `std` for reference)

### PR DESCRIPTION
**Pull request by holykol**
Resolves #180

### CODE REVIEW

File: client-gen/src/lib.rs [hunk 1]
```diff
@@ -4,7 +4,10 @@ use anyhow::{Context, Result};
 use convert_case::{Case, Casing};
 use std::{ffi::OsStr, fs, path::Path};
 
-pub fn generate_client_from_idl(idl_path: &Path, out_path: &Path) -> Result<()> {
+pub fn generate_client_from_idl<P: AsRef<Path>>(idl_path: P, out_path: P) -> Result<()> {
```
Comment (DennisInSky) [inline client-gen/src/lib.rs:7]: This code requires P to be the same type for both arguments which might not be the case, so it is better to write
```suggestion
pub fn generate_client_from_idl(idl_path: impl AsRef<Path>, out_path: impl AsRef<Path>) -> Result<()> {
```

**Review by DennisInSky — APPROVED** [review]
